image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - dockerpush

build:master:
  stage: build
  only:
    - branches@eownis/docker-blynk
  except:
    - master@eownis/docker-blynk
  script:
    - docker build .

dockerpush:master:
  stage: dockerpush
  only:
    - master@eownis/docker-blynk
  script:
    - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - docker build -t ${DOCKERHUB_REPO}:latest .
    - docker push ${DOCKERHUB_REPO}:latest
